name: Build and Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Semantic version (vX.Y.Z)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.9"

      - name: Build Linux binary
        env:
          CGO_ENABLED: 0
        run: |
          go build -o yuklomba -ldflags="-s -w" ./cmd/api

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ inputs.release_version }}
          name: Release ${{ inputs.release_version }}
          files: |
            yuklomba
          body: |
            YukLomba Backend ${{ inputs.release_version }} Linux binary
