name: Build and Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Semantic version (vX.Y.Z)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.9"

      - name: Build Linux binary
        env:
          CGO_ENABLED: 0
        run: |
          go build -o main -ldflags="-s -w" ./cmd/api

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-${{ inputs.release_version }}-linux
          path: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
